name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch WakaTime Stats and Update README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          show_language: true
          show_os: false
          show_projects: false
          show_editors: false
          show_timezone: false
          show_commit: false
          show_lines_of_code: false
          show_language_per_repo: false
          show_loc_chart: false
          show_days_of_week: false
          show_profile_views: false
          show_short_info: false
          show_updated_date: false
          show_total_code_time: false
